# Generated by Django 4.1.2 on 2022-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_employee_last_name_employee_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=38),
            preserve_default=False,
        ),
    ]
