# Generated by Django 4.1.2 on 2022-10-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_vehicles_vehicleadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleAdmin',
        ),
    ]
