# Generated by Django 4.1.2 on 2022-10-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_delete_vehicleadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='own_vehicles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vehicles'),
        ),
    ]
