# Generated by Django 4.1.2 on 2022-10-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_vehicles_horse_powers_vehicles_year_of_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='own_vehicles',
            new_name='own_vehicle_brand',
        ),
    ]
