# Generated by Django 4.1.2 on 2022-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_own_vehicles_employee_own_vehicle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='is_hybrid',
            field=models.BooleanField(null=True),
        ),
    ]
