# Generated by Django 4.1.2 on 2022-10-07 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_employee_options_employee_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicles',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
