# Generated by Django 4.1.2 on 2022-10-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
