# Generated by Django 4.1.2 on 2022-10-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='to_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.department'),
        ),
    ]
