# Generated by Django 4.1.2 on 2022-10-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_category_to_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='to_vehicle',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='to_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.department'),
        ),
    ]
