# Generated by Django 4.1.2 on 2022-10-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_employee_department_alter_vehicles_to_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Type of engine'},
        ),
    ]
