# Generated by Django 4.1.2 on 2022-10-10 11:09

from django.db import migrations, models
import models_demo.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(null=True, validators=[models_demo.web.validators.validate_after_today]),
        ),
    ]
