# Generated by Django 4.1.2 on 2022-10-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_department_name_alter_employee_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Power train'},
        ),
    ]
